apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-postgres
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-postgres
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: benflux_devtools_db
            - name: POSTGRES_USER
              value: benflux_user
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}-postgres-pvc
