apiVersion: apps/v1
kind: Deployment
metadata:
  name: benflux-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: benflux-api
  template:
    metadata:
      labels:
        app: benflux-api
    spec:
      imagePullSecrets:
        - name: ghcr-credentials
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          envFrom:
            - secretRef:
                name: benflux-api-secrets
          env:
            {{- range $key, $val := .Values.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
