image:
  repository: ghcr.io/benflux-company/benflux-devtools-api
  tag: 63d258c9e49161ea861e041640de1db130bf0e67
  pullPolicy: Always

service:
  port: 80
  targetPort: 4000

ingress:
  host: api.benfluxgroup.com

replicaCount: 1

env:
  NODE_ENV: production
  PORT: "4000"
