replicaCount: 1
image:
  repository: ghcr.io/benflux-company/benflux-devtools-api
  tag: 58248dce60965430654ef149055c03503128d446
  pullPolicy: Always
service:
  port: 80
  targetPort: 4000
ingress:
  host: staging.benfluxgroup.com
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 256Mi
env:
  NODE_ENV: staging
  PORT: "4000"
